stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw
    - src/prepare.py
    outs:
    - data/prepared/test.csv
    - data/prepared/train.csv
  trainXGB:
    cmd: python src/train.py XGBoost
    deps:
    - data/prepared/train.csv
    - src/train.py
    outs:
    - model/modelXGB.joblib
  trainRF:
    cmd: python src/train.py RandomForest
    deps:
    - data/prepared/train.csv
    - src/train.py
    outs:
    - model/modelRF.joblib
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - model/modelRF.joblib
    - model/modelXGB.joblib
    - src/evaluate.py
    metrics:
    - metrics/metrics_RF.json:
        cache: false
    - metrics/metrics_XGB.json:
        cache: false
