stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw
    - src/prepare.py
    outs:
    - data/prepared/test.csv
    - data/prepared/train.csv
  trainMLP:
    cmd: python src/train.py MLP
    deps:
    - data/prepared/train.csv
    - src/train.py
    outs:
    - model/modelMLP.joblib
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - model/modelMLP.joblib
    - src/evaluate.py
    metrics:
    - metrics/metrics_MLP.json:
        cache: false
