stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw
    - src/prepare.py
    outs:
    - data/prepared/test.csv
    - data/prepared/train.csv
  trainRF:
    cmd: python src/train.py RandomForest
    deps:
    - data/prepared/train.csv
    - src/train.py
    params:
    - paramsRF.criterion
    - paramsRF.max_depth
    - paramsRF.n_estimators
    outs:
    - model/modelRF.joblib
  trainXGB:
    cmd: python src/train.py XGBoost
    deps:
    - data/prepared/train.csv
    - src/train.py
    params:
    - paramsXGB.learning_rate
    - paramsXGB.max_depth
    - paramsXGB.n_estimators
    outs:
    - model/modelXGB.joblib
  trainSVC:
    cmd: python src/train.py SVC
    deps:
    - data/prepared/train.csv
    - src/train.py
    outs:
    - model/modelSVC.joblib
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - model/modelRF.joblib
    - model/modelSVC.joblib
    - model/modelXGB.joblib
    - src/evaluate.py
    metrics:
    - metrics/metrics_RF.json:
        cache: false
    - metrics/metrics_SVC.json:
        cache: false
    - metrics/metrics_XGB.json:
        cache: false
